require 'rake'
require 'ecstatic'

Ecstatic::Site.new(:sitedir => "site", :layoutfile => "standard.rbhtml",
                   :filesdir => "files", :modelsdir => "models",
                   :sitetitle => "Demo", :templatesdir => ".",
                   :datadir => ".", :navfile => "sitenav.yaml",
                   :indexfile => "siteindex.yaml").tasks

task :default => :website

desc "Upload website to server."
task :upload => :website do
  puts "Not implemented!"
  # Insert your own uploading code here, using rsync or whatever...
end
