require 'rake'
require 'ecstatic'

Ecstatic::Tasks.website

desc "Upload website to server."
task :upload => :website do
  puts "Not implemented!"
  # Insert your own uploading code here, using rsync or whatever...
end
