require 'rake'
require 'ecstatic'

Ecstatic::Site.new.tasks

task :default => :website

desc "Upload website to server."
task :upload => :website do
  puts "Not implemented!"
  # Insert your own uploading code here, using rsync or whatever...
end
